### DISCUSSION TITLE
React Native IOS build fails during pod installating in Github Actions (401 / 403)

### DISCUSSION THREAD

**Discussion by christian-hess-94** [rnmapbox/maps#3001] [Q&A]
## Environment
- Dev OS: [e.g. OSX 11.0.1, Win10]
macos-latest github action machine
## Steps to reproduce
Simply trying to install pods with fastlane inside the github actions machine gives the 401 error.

Error before trying to create .netrc file:
![image](https://github.com/rnmapbox/maps/assets/34290680/d97b785a-2e0c-4a55-b6a3-c294ce6e5d77)

Tried using an action that sets .netrc up with the machine, login and password values but still doesn't work.

Step that creates the .netrc config:
```yml
- name: Setup .netrc (MAPBOX)
        uses: little-core-labs/netrc-creds@v2.0.0
        with:
          creds: |
            [
              {
                "machine": "api.mapbox.com",
                "login": "mapbox",
                "password": "${{ secrets.MAPBOX_SECRET_KEY_STAGING }}"
              }
            ]
```
Error that happens:
![image](https://github.com/rnmapbox/maps/assets/34290680/09c092ac-d97c-46a9-9397-dc283e58bae7)

This is running the same fastlane action locally in the dev machine:
![image](https://github.com/rnmapbox/maps/assets/34290680/4796f458-08af-4fed-93ce-da2f12a84990)

This is the screen I'm creating with the app, it's pretty barebones and it renders correctly when running locally:
```tsx
export const MapScreen: React.FC<NotificationsPermissionScreenProps> = ({}) => {
  return (
    <ThemedScreenContainer hasLeftRightPadding={false} hasGradient>
      <Mapbox.MapView
        styleURL="mapbox://styles/gettruckup/clktpo0z701zj01p27sp72rsy"
        style={{ width: '100%', height: '100%', position: 'absolute' }}
      />
    </ThemedScreenContainer>
  );
};
```

It works locally on my dev machine: Macbook Pro M1. I can download and install pods without any problems and run it locally
